@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVkMzYwNzZjNDViOTZiYmZiM2MxYzQiLCJpYXQiOjE2NjcxMzc0MTQsImV4cCI6MTY2Nzc0MjIxNH0.v_I72940_Qc3dvVd5_sdi5DaiUsUDr0KkgJp0LkCjHE
GET http://localhost:8000/api/users/
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
Authorization: {{token}}