@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVkMzYwNzZjNDViOTZiYmZiM2MxYzQiLCJpYXQiOjE2NjgwMTMyMTksImV4cCI6MTY2ODYxODAxOX0.Z5HoriCOsJta7C9QkVh1yulqiUGAaWr-nTT40gA4M5k
POST http://localhost:8000/api/category/
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
Authorization: {{token}}

{
    "name": "JavaScript"
}